### ISSUE TITLE
Base Servicio de authenticacion

### ISSUE THREAD

**Issue by pcastelln** [alercebroker/user-microservices#2]
Servicio en Fast API que permite conectarse con google. Depende de tener definida la base de datos y colecciones.

Microservicio desarrollado en python con fastapi.
Solo se debe cumplit con el ciclo de oauth2, problemas de tokens y ralidator pendiente. 

Tareas
- [x] Los endpoints de oauth
- [x] Definir el punto del primer login y creacion de usuario (tener claro donde va a ir el codigo que se debe ejecutar, no definido aun que se va a hacer aqui)
- [x] Endpoint de metricas
- [ ] Tests unitarios
- [ ] Tests de integracion
- [x] Deployment

**Comment by AlxEnashi** [comment]
- Pobrar Google Oauth
- Tests
- Login con password

- Filtros y permisos - Modelo de datos
- Migrar datos
- Deploy
